android_library(
  name = "lib",
  srcs = glob(['src/main/java/**/*.java']),
  deps = [':res'],
  visibility = ['PUBLIC']
)

android_resource(
  name = 'res',
  res = 'src/main/res',
  package = 'com.buckbuild.scenario.lib1',
  resource_union = True,
  deps = ['//libs/lib2:res'],
  visibility = ['PUBLIC']
)
